### ISSUE TITLE
Preferred way to set resource_restrictions on workers

### ISSUE THREAD

**Issue by jmarkow** [dask/dask-jobqueue#194]
I'm using the `SLURMCluster` class to spin up workers on GCE.  Everything works great, but I'm wondering if I can set the `resource_restrictions` parameter easily either via dask-jobqueue or modifying the workers themselves.  In short, I'm trying to restrict the scheduler to run one task per node given roughly 1-2,000 tasks (submitted as `delayed` objects).

Hope this isn't a simple thing that I missed.

**Comment by jhamman** [comment]
@jmarkow - you can add arbitrary directives to the job submission via the `job_extra` keyword. There is a nice example of how this can be used for slurm here: https://dask-jobqueue.readthedocs.io/en/latest/examples.html#slurm-deployment-low-priority-node-usage

Does this seem like it will work for you?

Also, since you're running on GCE, I'm curious if you've looked at [dask-kubernetes](http://kubernetes.dask.org/en/latest/) at all. We've been using it on GCE quite extensively over the last year.

**Comment by jmarkow** [comment]
Interesting...I'll look into `job_extra` and report back.  

We actually were using Kubernetes previously, but since our university uses Slurm for our local cluster it's easier for others in our group to continue using the same scheduler.

**Comment by jmarkow** [comment]
OK I dug around, looked like I needed `extra` not `job_extra`, since this option needs to be appended to the `dask-worker` bash command, not appended to the sbatch header. 

e.g.

```python
cluster = SLURMCluster(processes=1,
                       cores=16,
                       memory='50GB',
                       queue='debug',
                       walltime='10:00:00',
                       extra=['--resources "TASKS=1"'])
```

**Comment by guillaumeeb** [comment]
It looks like it is tightly linked with #181. Except that if I understand correctly, you knew you were looking for how to specify resources.

So I believe your problem is solved?
