### ISSUE TITLE
shebang not used

### ISSUE THREAD

**Issue by spalkovits** [dask/dask-jobqueue#218]
Hello,
I conda installed dask_jobqueue on several machines. One cluster is using SLURM with bash as default, which works fine. On another cluster LSF is used together with zsh as shell. So I wanted to change the shebang in interactive mode like this:
```
cluster = LSFCluster(cores=2, memory='1GB', queue='default', shebang='!#/usr/env/bin zsh')
```
The job_script returned looks like this:
```
#!/bin/bash

#BSUB -J dask-worker
#BSUB -q default
#BSUB -n 2
#BSUB -R "span[hosts=1]"
#BSUB -M 1000
#BSUB -W 00:30
JOB_ID=${LSB_JOBID%.*}
```
I came around by editing core.py and hardcode the new shebang. But I ask myself what went wrong and how to correct it?

**Comment by lesteve** [comment]
@spalkovits, @willirath's suggestion should do what you need, as a work-around until the next release. Closing, feel free to reopen if your issue was not fixed somehow.

Having said that, I would be really curious why you want to change the submission script shell (the only reason I can find is if you want to use `env_extra` and use some shell-specific construct there but I may be missing something).
