### ISSUE TITLE
Why does LSFCluster try and force processes onto one host?

### ISSUE THREAD

**Issue by bnlawrence** [dask/dask-jobqueue#226]
https://github.com/dask/dask-jobqueue/blob/5a5585dffea0237e452792c7ed0b13d5d1e3f8bb/dask_jobqueue/lsf.py#L94

This seems to be an undocumented and unhelpful default. In our environment (JASMIN, where we can and do run cores across shared nodes) this will cause very slow queueing. It should be optional, and I can't see how to make it optional.

I can see from GH-172 why this has been put in, but it's the wrong solution to the problem (which is that you want to make this optional, it could even be the default if there was a clean and easy way to change it). One of us (at JASMIN) will eventually create a pull request to fix this ... but we have to get any sort of LSFCluster working in the first place (which we have yet to do)... but that's a story for another issue :-)

**Comment by bnlawrence** [comment]
(I should say that I can see that one might argue that since each job/worker combination is *intended* to be per node, you'd argue that i should just set 1 core per node and have lots of jobs, but I think that's an optimisation that you could leave to the user.)

**Comment by lesteve** [comment]
Thanks for opening an issue!

`LSFCluster` is not used by any of the active `dask-jobqueue` maintainers and it is quite likely that there is room for improvement. Any help on making `LSFCluster` better and maintaining it going forward would be more than welcome!

ccing @raybellwaves, @louisabraham and @adamhaber who seemed to be using `LSFCluster` at one point.

About your particular issue, I know very little about `LSF` but it seems to me like `span[hosts=1]` makes sense. Basically, each job is going to run a `dask-worker` command and each `dask-worker` needs to run on a single node. I am guessing this is more or less what you are saying in your latest comment (https://github.com/dask/dask-jobqueue/issues/226#issuecomment-457832861).

Trying to illustrate this with snippets, if you want to get 48 cores on different nodes (with 4 cores per node), you would do something like this:
```py
cluster = LSFCluster(cores=4, processes=1, memory='4GB')
client = Client(cluster)
# 12 jobs (very likely on different nodes)
# Each job uses 1 worker process and 4 threads per worker process
client.scale(12)
```

and NOT something like this:
```py
cluster = LSFCluster(cores=48, processes=12, memory='48GB')
client = Client(cluster)
# 1 job on a single node
# Each job uses 12 worker processes and 4 threads per worker process
client.scale(12)
```

**Comment by bnlawrence** [comment]
Thanks for getting back to me. I guess the heart of the matter comes down to the difference between processes, threads and workers. If I am not yet familiar enough with DASK to know how it affects DASK itself, but I would have thought that the situation where I want to have *threads* being shared on a node is different from having *processes* shared on a node. 

In particular, I can your first example is using threaded parallelism, but one could also have done hte following:

```python
cluster = LSFCluster(processes=4, memory='4GB')
client = Client(cluster)
# 12 jobs (very likely on different nodes)
# Each job uses 4 worker processes
client.scale(12)
```

Is that nuts? If it isn't, then I'm not sure why I would *necessarily* want to have all four processes on one node. I might, but I might not, and that might depend on the load and queuing environment.

So, I understand why we might *want* to do this, I am must not sure that I should *have* to do this.

**Comment by lesteve** [comment]
> Is that nuts? If it isn't, then I'm not sure why I would necessarily want to have all four processes on one node. I might, but I might not, and that might depend on the load and queuing environment.

It may make sense in some cases. IIRC some users (maybe @jhamman?) were tweaking the per-node mix of processes and threads depending on their workflows.

In the case where you don't care about having multiple worker processes on the same node, I would suggest using `processes=1` (this is probably what you were saying in https://github.com/dask/dask-jobqueue/issues/226#issuecomment-457832861).

In other words, `dask-jobqueue` is trying to use the queuing system (i.e. `LSF` in your case) in the dumbest way possible. IMO all the smartness in is the `dask` scheduler. For example:
* the `dask` scheduler can decide which worker to send the computation to depending on which worker has the data needed for the computation
* the `dask` scheduler can detect that a worker has died during a computation (e.g. in `dask-jobqueue` context because one of the job had gone over its walltime) and reschedule the computation on another worker 
* adaptive settings, the number of jobs can be scaled up and down depending on amount of work sent to the scheduler
* work stealing between workers
* etc ...

**Comment by bnlawrence** [comment]
Thanks. I think I agree that the right thing to do most of the time is to set up loads of 1 process workers and leave it to DASK.  In the event of multiple process workers, then there probably needs to be a reason why you 'd do that, which probably means some sort of affinity would be a good thing (TM), which probably makes the `span[hosts=1]` the right thing, but I don't like it being mandatory (what if the only reason you are doing it is that you are only allowed so many jobs in the queue, but your job can start sooner if it doesn't need all the slots on one host).  As I say, at some point we'll generate a pull request, and then someone can decide :-).

**Comment by lesteve** [comment]
Hopefully you'll manage to get `dask-jobqueue` to work on your cluster.

IMO, what would be extremely useful, would be PRs that improve the documentation on the points that you found confusing or that tripped you up when getting `dask-jobqueue` to work. There is certainly a big margin for improvement there, especially for people that are familiar with their queuing sytem but not so much with `dask`.

**Comment by guillaumeeb** [comment]
IIRC, the original problem you described is due to considerations about simplicity of codebase and constraint of some queuing system. PBS and SGE does not handle spawning process on several hosts easily like Slurm with `srun` and LSF with probably something equivalent.

So we decided to adopt a common approach for every job schedulers.

I vaguely remember a nice comment by @jhamman explaining this original choice, but I couldn't find it.

I agree that Slurm and LSF could do more powerful things, and I'm personnaly open to any change in that direction, provided it does not introduce a lot of specificities for this schedulers.

**Comment by lesteve** [comment]
> I agree that Slurm and LSF could do more powerful things, and I'm personnaly open to any change in that direction, provided it does not introduce a lot of specificities for this schedulers.

IMO having a common and simple mental model for all the queuing systems is crucial for maintenance reasons.

I'd rather stay clear of queuing system specific feature/behaviour/optimization unless there is an extremely good reason behind it.

**Comment by lesteve** [comment]
What I was trying to say is that I really like the fact that `dask-jobqueue` is based on a common denominator of all the supported queuing system features.

Right now, the only queuing system specific thing you need is how to submit a job on a single node booking a number of cores. Once you have your job you run `dask-worker` using all the booked cores and from then on you don't need to think about your queuing system specificities.

My guess is the following: the kind of tricks that cluster power users are used to don't have as much importance when you use `dask`. I may be wrong of course and I'd be happy to revisit this, if it turns out that the "common denominator" approach is severely limiting what people want to do with `dask` on `HPC` clusters.

While I think of it, another aspect we would need `LSF` experts on, is to add `LSF` to our CI infrastructure. If you know how to install `LSF` I am assuming this should not be too much effort to create `docker` and `docker-compose` files to add it in our CI. A PR on this would be really great and I'd be more than willing to help on this !
