### ISSUE TITLE
NERSC How to run dask-jobqueue on interactive node + use it in python script

### ISSUE THREAD

**Issue by rjdirisio** [dask/dask-jobqueue#259]
Hello,

I am new at using dask and dask-jobqueue, and hope to use it to perform a multitude of Python subprocesses at once (~5000) on Cori, combining it with joblib.  I discovered a previous thread where a NERSC Cori tutorial was added.  In the new documentation on [dask-jobqueue's website](https://dask-jobqueue.readthedocs.io/en/latest/configurations.html#nersc-cori), the example says I should obtain an interactive node using `$ salloc -N 1 -C haswell --qos=interactive -t 04:00:00` and then run jobqueue directly on it.  However, I am confused by this.  In my sbatch script (which I am running from $SCRATCH) should I salloc the interactive node and then somehow call it in my python script when I do clutser = SLURMCluster()? I copy and pasted the .yaml file into my `~/.config/dask/` directory as well.

**Comment by guillaumeeb** [comment]
Hi @rjdirisio,

cc @costrouc and @josephhardinee 

I'm not sure what your problem is. If it is not possible to instantiate a SLURMCluster from your cluster access node, then yes, you should do it from a compute node, by submitting a job first.

If you want to do that interactively:
- Launch an interactive job
- Open you Ipython console or equivalent, and create a SLURMCluster

If you want to do that in batch mode:
- Submit a job in which you run your Python code creating the SLURMCluster.

Just beware in the second case, you want to have a walltime big enough for you main job, it should last the entire computation. Another solution in this case is to use https://github.com/dask/dask-mpi.

**Comment by rjdirisio** [comment]
Thanks!
Just as an fyi, I don't think one has to use the interactive node to run the client, as it says in the documentation, they can just submit a batch job that calls a client+cluster within a python script to request more nodes.
