### ISSUE TITLE
Workers not identified

### ISSUE THREAD

**Issue by kforti** [dask/dask-jobqueue#262]
When I start workers on an LSF cluster the jobs are started but the client does not acknowledge the workers. If I submit tasks to the cluster they are never executed because there are no workers to perform the execution. I know the jobs are indeed starting because I can see them on my system with the bjobs command.

This just started happening. Everything was running fine for a few months.

```
cluster = LSFCluster(queue='short', processes=4, walltime='2:00', ncpus=4, mem=2024, cores=4, memory='2 GB') 
client = Client(cluster)
cluster.scale(8)
cluster 
```
Output
`LSFCluster(cores=0, memory=0 B, workers=0/8, jobs=0/2)`

This does not change even after the jobs start running.

**Comment by lesteve** [comment]
Weird, especiallly the "this just started happening" since nothing has changed on the dask-jobqueue side (last dask-jobqueue release was in October 2018).

What you are seeing seems to indicate that the LSF jobs start but that the dask workers do not manage to connect to the scheduler.

The few things I would suggest:
* make sure that you are using the same conda/virtualenv environment where you run the snippet above and in your workers. Sometimes a good sanity check is to create a new conda/virtualenv environment from scratch and see whether the problem is still here.
* have a look at https://jobqueue.dask.org/en/latest/debug.html to troubleshoot your problem. In particular, I would look at your LSF logs stdout/stderr logs to see whether there is any indication of where the problem might be and also increase the logging verbosity.

**Comment by kforti** [comment]
Thank you for your suggestions. Things are working as expected today. Not sure what happened, it is likely something to do with the cluster. I will close this issue for now.
