### ISSUE TITLE
dask dashboard not showing workers after cluster.stop_workers(cluster.jobs)

### ISSUE THREAD

**Issue by apatlpo** [dask/dask-jobqueue#28]
On PBS with dask-jobqueue #25 
If I start a cluster, kill workers with `cluster.stop_workers(cluster.jobs)`  and try to restart a new cluster, then workers do not show up in the dashboard.
Is it expected behavior?
Could we do something about this?

**Comment by apatlpo** [comment]
I should also mention that the new set of worker seem to be working correctly

**Comment by guillaumeeb** [comment]
@apatlpo can you describe precisely the commands you are launching? Are you using `cluster.restart()`?

If so, I imagine it is failing because we do not update worker launching command to point to the new scheduler address (scheduler port is probably changing on restart).

But you could achieve something similar by only launching `cluster.start_worker(n)` or `cluster.scale_up`.

**Comment by mrocklin** [comment]
Unrelated note, but the scheduler port should not be affected during a
restart.  In general the cluster managers (like dask-jobqueue) shouldn't
have to care much about restart events, that should be handled well within
dask itself (hypothetically at least).

**Comment by guillaumeeb** [comment]
Obviously you are right @mrocklin. We'll wait for @apatlpo to clarify.

**Comment by apatlpo** [comment]
I believe this was just noise on my part, deeply sorry.

It works fine today with:
```

cluster.stop_workers(cluster.jobs)
```
and then:
```
cluster.start_workers(4)
```
Even `client.restart()` and `client.upload_file()` are working.

I have other issues (workers dying) but these will motivate other posts. 

Sorry again
