### ISSUE TITLE
job_extra, extra and env_extra naming could be improved

### ISSUE THREAD

**Issue by lesteve** [dask/dask-jobqueue#323]
* `job_extra` -> `job_header_extra`
* `env_extra` -> `job_script_extra`? Not great, better suggestions welcome! Not sure if there is a good way to indicate that this is something which is at the beginning of the script but after the shebang and job header (and before we run dask-worker).
* `extra` -> `dask_worker_additional_args`, better suggestion welcome!

We may want to want to warn for a few releases and point to the new name parameter names, same thing for values from the config `job-extra` and `env-extra` if they are used.

**Comment by guillaumeeb** [comment]
I agree that the naming is not ideal, but do we really want to modify it? I'm not sure...

That said, that's not a strong opposition.

In batchspawner, `env_extra` is called `prologue`, https://github.com/jupyterhub/batchspawner/blob/master/batchspawner/batchspawner.py#L507.

**Comment by mrocklin** [comment]
We can always make a choice to break many APIs, and announce a major version bump.  

Most dask-jobqueue users today are early adopters, and would probably be tolerant of such an action.  It might be worth thinking about what other API changes we might want to make.

**Comment by lesteve** [comment]
This seems another candidate for breaking API changes, we have both `mem` and `memory` in `LSFCluster`:
https://github.com/dask/dask-jobqueue/issues/205

**Comment by riedel** [comment]
One could easily have both and add a [deprecation warning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning), so I would argue that there could be coexisting until a major bump.

**Comment by jolange** [comment]
I'd like to give this a shot soon, because I'm eager to have possible changes included in the next release.

> One could easily have both and add a [deprecation warning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning), so I would argue that there could be coexisting until a major bump.

@riedel I agree, but to my understanding, a [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning) would be better suited. In the used terminology, I think we want to warn "end users", not only "other developers".
If I add a `DeprecationWarning` in `Job` and run a script instantiating a `*Cluster`, the warning will be suppressed by default.
See also [below this table](https://docs.python.org/3/library/warnings.html#warning-categories):
> Changed in version 3.7: Previously [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning) and [FutureWarning](https://docs.python.org/3/library/exceptions.html#FutureWarning) were distinguished based on whether a feature was being removed entirely or changing its behaviour. They are now distinguished based on their intended audience and the way they’re handled by the default warnings filters.

**Comment by guillaumeeb** [comment]
@jolange :+1 on the `FutureWarning` if you're willing to implement that!

**Comment by jolange** [comment]
Alright, but I think there was no final decision about the names yet, right?

The proposals up to now were:
`job_extra`: `job_header_extra`
`env_extra`: `job_script_extra`, `prologue`
`extra`: `dask_worker_additional_args`

For `job_extra` I would propose `submit_file_extra`.
For `env_extra` I would propose `job_prologue`. (At least something that indicates that it is run *before*.)
The third one sound fine to me.

What do you think? Do we need a vote? :laughing:

**Comment by riedel** [comment]
I wonder if job_extra could not be simply kept. For slurm it is the same as  adding command line flags and file should probably not be overemphasized. The sbatch man page  does not know a submit file it is a batch file. So job_extra is somehow neutral IMHO. submit_extra would IMHO also work, but I see limited benefit in renaming. If renaming it would be cool to allow dictionary style arguments leaving away the -- for slurm (using a none value to omit the '=') . As dictionaries are ordered since python 3.6 this could work. For me it would mean a lot of convenience when setting walltime etc.

**Comment by jolange** [comment]
Keeping `job_extra` would be fine for me -- I just checked if all Cluster-Classes using it put it in the file, not if the terminology is really suited. By the way, that would also be the most tedious of the three to rename.
What I personally care about is `env_extra`, because I think it is misleading. And `extra` looks like it would be an easy change and it could really be more expresive.

> would be cool to allow dictionary style arguments

That's actually the case for HTCondor already, because that also uses key-value pairs anyway. (For all others it's a list.)

**Comment by guillaumeeb** [comment]
My 2 cents:
- job_extra --> job_extra_directives. There is a concensus in several batch system for directives. Maybe not with Condor. I'm also okay to leave it untouched.
- env_extra --> job_script_prologue. job_prologue could be misleading for PBS where such a thing exists outside of the main script. Prologue leaves room for an epilogue, which could be useful.
- extra --> worker_extra_args. I think dask can be removed here. And I'd like to keep extra in it.

For the dictionary style value for directives, I'd say if you feel it's important, please do it in another PR.

**Comment by jolange** [comment]
Alright, I started with the renaming of `env_extra` in #575. `job_script_prologue` sounded like a good suggestion.

**Comment by guillaumeeb** [comment]
Before I forget what people think about job_extra_directives?

**Comment by riedel** [comment]
> Before I forget what people think about job_extra_directives?

I at least like this name best among the proposed ones. I think even htcondor users can abstract from “commands” to “directives”. It would remove the last bit of ambiguity, I guess. If @jolange has a run, why not ;) Thx btw.

**Comment by jolange** [comment]
I personally would have left it unchanged, but if you both think `job_extra_directives` adds clarity, I can take care of that.

**Comment by jacobtomlinson** [comment]
I have no strong feelings here, but I don't have much experience with htcondor so maybe that's why.

**Comment by guillaumeeb** [comment]
> but I don't have much experience with htcondor so maybe that's why.

As it would be the same keyword for each queuing system, do you find it adapted to those you may know?

**Comment by jolange** [comment]
I did not see any objection to `job_extra_directives`, so I assume I can move on with it?

**Comment by guillaumeeb** [comment]
That would be really nice!

**Comment by jolange** [comment]
When this is done, should I create an issue to remove the deprecated parameters in a future release?

**Comment by guillaumeeb** [comment]
Yes please, that would be welcomed!

**Comment by riedel** [comment]
Just as a general comment regarding the new `job_script_prologue`. I just now had a problem with slurm prologs and I was really surprised to see how many different variants of prologues  there are: https://slurm.schedmd.com/prolog_epilog.html. It all boils down to good documentation in the end, I guess. However, I just now realized how important it was to have "script" in the name. Should be fine.
