### ISSUE TITLE
start_workers property in LSF

### ISSUE THREAD

**Issue by zqwei** [dask/dask-jobqueue#359]
It seems like `start_workers` is no longer supported in LSF after 0.7, is there any replacement we can use? Many thanks!

**Comment by stuarteberg** [comment]
Your issue is most likely related to the recent change to how workers are launched.  You should try the new config setting `use-stdin` as mentioned here: https://github.com/dask/dask-jobqueue/issues/328#issuecomment-541927282.

Note: for now, you must configure this option via the config, not via the `LSFCluster` constructor.

```python
dask.config.set({"jobqueue.lsf.use-stdin": True})
```

But I'm working on a PR that will allow passing it to the constructor, too.

**Comment by stuarteberg** [comment]
Oops, I see that we work in the same building.  Hah!  I think Davis was going to spread the word about this issue.  Maybe you've already fixed your config by now...

**Comment by mrocklin** [comment]
The start_workers method was removed.  Please use scale instead.
