### ISSUE TITLE
Support for Altair Accelerator

### ISSUE THREAD

**Issue by ignamv** [dask/dask-jobqueue#413]
Hi,

I've been using Dask on a cluster that runs [Altair Accelerator](https://www.altair.com/accelerator/). I've been mostly launching the workers manually, but I have some rough code (based on the LSF cluster module) to launch them using dask-jobqueue. I was wondering whether you'd be interested in this, and what I would have to provide (minimum functionality, tests, etc).

Regards
Ignacio

**Comment by lesteve** [comment]
> I've been using Dask on a cluster that runs Altair Accelerator. I've been mostly launching the workers manually, but I have some rough code (based on the LSF cluster module) to launch them using dask-jobqueue.

Great to hear that the `dask-jobqueue` code has already been useful for you!

I have never heard of Altair Accelerator so out of curiosity:
- where is it used mostly, academia, companies, any particular type of companies ?
- does it look like a job scheduler that we already support (you started with the LSF code so it may look like LSF a little bit) ?

> I was wondering whether you'd be interested in this, and what I would have to provide (minimum functionality, tests, etc)

This is a very good question and the answer is I don't really know ... there is a cost/benefit analysis that is rather tricky to do.

In particular it depends on:
- how likely it is to be used by other people 
- how different is Altair Accelerator from the job schedulers we already support
- how much code does it would add to `dask-jobqueue`
- for adding tests how easy it is to have a Docker image with a toy cluster

Because I am a maintainer in `dask-jobqueue` (and variety of other small reasons e.g. I have never heard of Altair Accelerator before, it seems proprietary, etc ...) I will tend to err on the conservative side, so my current personal recommendation would be to encourage you to put together a package and see where it leads you.

**Comment by ignamv** [comment]
You're right, it seems very niche: I can hardly find people asking about it on Google. My company uses it mostly to run electronics CAD simulations. I believe it's related to LSF because it includes wrapper scripts and instructions for people migrating from LSF. I don't believe there's a free version we could use for testing.

I'll publish my code for fun on a fork but it's probably not worth maintaining on the main branch.

**Comment by lesteve** [comment]
That makes sense, thanks a lot for the details and your understanding!

**Comment by guillaumeeb** [comment]
Hi, just to say that Altair is the company that is behind PBS Pro scheduler, which has already a licensed version (and a dask-jobqueue implementation). So it's a little weird to see another job queueing system from them? The website of Altair is currently down, so I cannot see how this differs from PBS.

**Comment by ignamv** [comment]
It looks like PBS is set up using comments on a shell script, while Accelerator uses command-line arguments in the submission command (`nc run`)
