### ISSUE TITLE
New Github design shows oldest release as latest?

### ISSUE THREAD

**Issue by willirath** [dask/dask-jobqueue#446]
The new side bar seems to get the order of releases wrong. It lists the v0.1 as the latest release:

![image](https://user-images.githubusercontent.com/5700886/85598583-03752500-b64c-11ea-8e6a-964edfb31d00.png)

(Not sure if this is something that can be fixed in this repo or if this is a bug with Github.)

**Comment by mivade** [comment]
That's odd. Clicking on the `+12 releases` link shows things in the right order, so I'm guessing this is an issue with the redesign. I submitted a GitHub support request for this since I'm not sure how else to inform them of this.

**Comment by willirath** [comment]
I think this is because of the distinction between releases and tags that [Github is making](https://help.github.com/en/github/administering-a-repository/about-releases). And `0.1.1` is the latest tag that also is a proper release.

To fix this, I'll add this step to the release procedure docs.

**Comment by willirath** [comment]
See #447.

**Comment by lesteve** [comment]
Thanks for noticing this!

As a quick fix, I removed the old releases now there are only tags.

I looked at a few Dask projects (distributed, dask, dask-kubernetes) and none of them seem to be using releases, maybe this would be a conversation to have in `dask/community`?

I have to admit I don't really know the the advantages of having Github releases besides looking better in the web UI.

One thing I noticed is that since we are using only tags, it is harder with the new Github interface to access the list of releases, i.e. there does not seem to be any direct link that you can click on.

**Comment by willirath** [comment]
> I looked at a few Dask projects (distributed, dask, dask-kubernetes) and none of them seem to be using releases, maybe this would be a conversation to have in dask/community?

Agreed. I'll switch the PR to a draft to avoid merging before this is clearer.

**Comment by willirath** [comment]
On this note: While Github releases feel comfortable, they're a big move to vendor lock in. As we don't _need_ them, because we rely on PyPI for distribution anyway, sticking to tags is the way to go for me.

**Comment by lesteve** [comment]
OK closing this issue then!
