### ISSUE TITLE
Dask distributed using login node's RAM during script execution

### ISSUE THREAD

**Issue by bhanu-magotra** [dask/dask-jobqueue#452]
While running a jupyter notebook on one of the login nodes of HPC,  I am able to use PBSCluster() to request a cluster of around 200 GB of RAM with 20 workers. I am also successfully able to link the the client with cluster. 

When I execute my script, which involves working with a netcdf datset of around 140 GB, the workers are running properly but the RAM on the login node gets used up to 97%  of 134 GB total, before I have to kill the kernel manually or risk getting flagged by admin.

I am not able to understand why the login node's RAM is being consumed while working with dask workers which are obviously running on computation nodes?
Please help me get to the possible reason for this weird behaviour.

![Screenshot from 2020-07-16 17-25-37](https://user-images.githubusercontent.com/60338532/87696968-2f00b080-c7af-11ea-87a4-be8f27df2ae1.png)

**Environment**:

Dask version: 2.19.0
Python version: 3.7.7
Operating System: CentOS Linux 7 (Core)
Install method (conda, pip, source): conda and pip

**Comment by willirath** [comment]
What exactly is your calculation doing? Dask does not prevent you from filing up memory on the client side.

**Comment by bhanu-IITD** [comment]
After requesting the cluster and connecting the client , I have to execute the below code which is then followed by some plotting. Initially , I was trying to follow [this](https://stackoverflow.com/questions/62920660/identifying-the-inefficiency-and-bottleneck-in-my-approach-with-dask-and-xarray) approach which was too inefficient. Therefore, I decided to load the required dataset into memory to speed up the execution but here it is getting spilled into login node's RAM.

## Load the complete LIS outputs as xarray datasets ##
```
lsmdat=xr.open_mfdataset('../SURFACEMODEL/*/*HIST*',combine = 'by_coords', parallel = True,autoclose=True)
routedat=xr.open_mfdataset('../ROUTING/*/*HIST*',combine='by_coords' , parallel = True,autoclose=True)])

routedat_1 = routedat[['Streamflow_tavg','RiverDepth_tavg','FloodedFrac_tavg']].sel(time=slice('1964-01-01', '2014-12-31'))
lsmdat_1 = lsmdat[['TotalPrecip_tavg','Evap_tavg']].sel(time=slice('1964-01-01', '2014-12-31'))
lsmdat_2 = lsmdat['SoilMoist_tavg'].sel(time=slice('1964-01-01', '2014-12-31'))

routedat_1.load()
lsmdat_1.load()
lsmdat_2.load()
route_flow = routedat_1['Streamflow_tavg'].to_dataframe()
route_flow.reset_index(inplace=True)
```

**Comment by willirath** [comment]
Xarray's `.load()` will bring all the data to numpy arrays on the front end.

**Comment by bhanu-magotra** [comment]
Which is exactly what I want, but on cluster's RAM and not login node's from where I am running the script. Is it possible? Given the fact that I have successfully connected  client to the cluster prior to executing any thing.

**Comment by andersy005** [comment]
> Which is exactly what I want, but on cluster's RAM and not login node's from where I am running the script. Is it possible?

It sounds like you need to use `.persist()` instead of `.load()`

```python
routedat_1 = routedat_1.persist()
lsmdat_1 = lsmdat_1.persist()
lsmdat_2 = lsmdat_2.persist()
```

**Comment by bhanu-magotra** [comment]
> > Which is exactly what I want, but on cluster's RAM and not login node's from where I am running the script. Is it possible?
> 
> It sounds like you need to use `.persist()` instead of `.load()`
> 
> ```python
> routedat_1 = routedat_1.persist()
> lsmdat_1 = lsmdat_1.persist()
> lsmdat_2 = lsmdat_2.persist()
> ```

Thanks, I will try this and report back.

**Comment by bhanu-magotra** [comment]
Using `.persist()` definitely restricted RAM consumption on login node. But, now I am back to my [first](https://stackoverflow.com/questions/62920660/identifying-the-inefficiency-and-bottleneck-in-my-approach-with-dask-and-xarray) problem.  
`.persist()`  is still lazily loading the datasets and hence my outputs are very slow. 
So, how do I now load xarray datasets eagerly into **cluster's RAM** ?

**Comment by andersy005** [comment]
> .persist() is still lazily loading the datasets and hence my outputs are very slow.

The xarray dataset/datarray may still show you that it contains dask arrays, however with the `.persist()`call,  your data is now distributed as numpy arrays in your cluster. 

One way to confirm this is to inspect the task graph right before and after calling `.persist()`, you will notice that your tasks graph look different:

- before

![Screen Shot 2020-07-16 at 1 17 31 PM](https://user-images.githubusercontent.com/13301940/87713124-f341f880-c766-11ea-8305-ca89f08dd9bf.png)

- after

![Screen Shot 2020-07-16 at 1 17 37 PM](https://user-images.githubusercontent.com/13301940/87713136-f76e1600-c766-11ea-8308-456c4306602c.png)


The slowness of your workflow is likely due to the nature of your computation or your chunking scheme and not dask/dask-jobqueue. You may want to look into the resulting chunking scheme after the `open_mfadataset()` calls:

```python
lsmdat=xr.open_mfdataset('../SURFACEMODEL/*/*HIST*',combine = 'by_coords', parallel = True)
routedat=xr.open_mfdataset('../ROUTING/*/*HIST*',combine='by_coords' , parallel = True)
```

**Comment by bhanu-magotra** [comment]
> The xarray dataset/datarray may still show you that it contains dask arrays, however with the `.persist()`call, your data is now distributed as numpy arrays in your cluster.

Ok. Thank you for explaining.

> The slowness of your workflow is likely due to the nature of your computation or your chunking scheme and not dask/dask-jobqueue. You may want to look into the resulting chunking scheme after the `open_mfadataset()` calls

Yes. it seems like I am working with very small chunk size (1x300x300) * 4 bytes) which is creating large number of tasks. Now I have increased the chunksize with 'time':350. I was reading here that a chunk size of 1 GB is good if you have 20 cores with 200 GB RAM. I tried with chunking along time dimension with` 'time':2555` to make it 1 GB chunk. I also tried 'time':300 , 700 and 1500. But the execution got slower in each case. Can you please give some suggestions?
This is how my dataset looks without any chunking.
![2020-07-17_07-39](https://user-images.githubusercontent.com/60338532/87741978-64cf8480-c803-11ea-9f4f-e404af04e9bc.png)

**Comment by willirath** [comment]
Your timings (O(hours) for O(100GB)) don't really look like anything that is related to hardware limits (CPU, memory bandwidth, IO bandwidth).

Looking at the [linked Stackoverflow posts](https://stackoverflow.com/q/62790618/10052956), I noticed
> The datasets have netcdf files for each day.

Is this also true here? If so, I'm quite sure that ultimately this is the root of your problems:

1. Xarray's `open_mfdataset` can be quite slow for many netCDF files especially if you use a large Dask cluster (because for combining by coords, there will be lots of reading of small amounts of data which all happen on the distributed cluster with latencies piling up.) A possible way around is using a [single-threaded scheduler](https://docs.dask.org/en/latest/setup/single-machine.html#selecting-threads-processes-or-single-threaded) just for the `open_mfdataset` call:
```python
with dask.config.set(scheduler='single-threaded'):
    ds = xarray.open_mfdataset(...)
```

2. As IO is per file, there will always be chunks with `"time": 1` in your task graph. You'll notice that no matter what the `chunks` keyword of `open_mfdataset()` says, chunking won't cross file boundaries. You can group these single-time-index chunks into bigger chunks later (e.g. `ds = ds.chunk({"time": 365})`) though. (More problems and how to overcome these below.)

3. With your cluster topology (many single-threaded workers) all communication between workers is via the network link (this is true even if they're on the same machine). When, re-chunking `"time": 1` into something else, Dask will spread out `getitem, rechunk-split` tasks to all workers and then communicate all the `rechunk-split` results to one worker where `rechunk-merge` happens. To overcome this, you usually want to use multi-threaded workers. I'm not sure about your cluster, but try with `cores=20` and `processes=1` (or anything that fits memory and CPU limits per node).

4. Depending on the complexity of what you want to do with the data eventually, it may help to persist the re-chunked data. Or it might not be necessary to rechunk at all (because you won't be able to avoid having the 1x300x300 chunks in intermediate steps anyway).

Having said all this and noting that your frontend seems to be well-sized for the data volume we're talking about here, it could be wise to not scale out to many nodes, but to work with a `LocalCluster` at least until you have a feeling for where the pitfalls are:

```python
from dask.distributed import LocalCluster, Client
import xarray as xr

# Play with different numbers of workers and threads per worker
# (keeping 8 in total) to see effect of topology:
cluster = LocalCluster(n_workers=1, threads_per_worker=8, memory_limit=16e9)
client = Client(cluster)
display(client)  # if any possible, look at the dashboard!

ds = xr.open_mfdataset('../SURFACEMODEL/*/*HIST*', combine='by_coords')

# calculate time-variance of horizontal mean
# take timing, e.g., with %%time in a Jupyter Notebook cell
display(ds.mean(dim=["lon", "lat"]).var("time").compute())

# repeat with re-chunking
# take timing, e.g., with %%time in a Jupyter Notebook cell
display(ds.chunk({"time": 1000}).mean(dim=["lon", "lat"]).var("time").compute())
```

**Comment by willirath** [comment]
@andersy005 I'm not sure if this is a good place for this discussion, as it's not really about any Jobqueue specifics, but I tend to not move this anywhere else, because it nicely show that scaling out to the big machine is hardly ever the first thing to do.

**Comment by andersy005** [comment]
> @andersy005 I'm not sure if this is a good place for this discussion, as it's not really about any Jobqueue specifics,

I concur. Feel free to remove the `usage question` label if need be.

**Comment by lesteve** [comment]
Thanks for the discussion I found it interesting!

I am going to close this one since it seems the discussion has reached its end. Feel free to reopen if needed.
