### ISSUE TITLE
Scale the number of dask workers to available resources on HPC

### ISSUE THREAD

**Issue by MarieNyst** [dask/dask-jobqueue#457]
When using dask on a HPC, it would be useful to be able to automatically scale up or down the number of dask workers based on how much free resources there are.

A simple use case would be:
I launch my computations, there are 20 free nodes. Dask sees that and starts 100 workers to get those nodes allocated.
1 hour later, a colleague launches something that is now in the queue. Dask sees that and each time a worker finishes a computation it terminates it until the queued jobs start.
A few hours later, my colleague gets their results and dask starts new worker to claim unused resources.

I thought that it was what the [adapt](https://docs.dask.org/en/latest/setup/adaptive.html) function was all about. Then understood that it doesn't adapt to the cluster scheduler load but to dask scheduler load.

Now, most of my researches point to this adapt method. Either because what I'm asking doesn't exist or because it is not so much used...

**Comment by ocaisa** [comment]
I would probably see this as more of a policy choice you would need to iron out with your site, it might not be appreciated that dask-jobqueue continuously polls the resource manager (this can make it clunky for everyone else...and how would you deal with multiple Dask users trying to use this feature at once). Rather than have Dask monitor the scheduler workload, you could work together with the site so that they would allow idle nodes/resources to be (automatically) added to a pool of resources for a pre-emptable queue (since Dask can recover from resources being pulled from the queue). Then you could just submit normal jobs to that particular queue leveraging the existing adapt method. If the utilisation on that queue were high enough, you could ask that they consider assigning a minimum set of resources to it.

On the sites that I have access to, it hasn't been the available resources but the number of allowed simultaneous jobs that have been the limiting factor.  Having a special queue would also allow these restrictions to be looser.

**Comment by MarieNyst** [comment]
> it might not be appreciated that dask-jobqueue continuously polls the resource manager

True, though it doesn't need to happen continuously, it could be just a regular ping.

> how would you deal with multiple Dask users trying to use this feature at once

I'm not sure, but wouldn't it work if the new workers were not sent all together at the same time? As in, sending new workers and making sure they started before sending more?

>Rather than have Dask monitor the scheduler workload, you could work together with the site so that they would allow idle nodes/resources to be added to a pool of resources for a pre-emptable queue. Then you could just submit normal jobs to that particular queue leveraging the existing adapt method. 

I understand. My issue with this approach is that I have no maximum number of jobs. I would want to have about 600 workers when the cluster is empty. But if I use the current adapt method I will have 600 queued jobs waiting for resources when the load is high and this is when things get clumsy.

**Comment by guillaumeeb** [comment]
Thanks @MarieNyst for this good question.

I agree with @ocaisa here : overall, this is more a job queueing system tunning, that should not be in dask-jobqueue. Your job queuing system is responsible for the load between user and jobs priority.

> But if I use the current adapt method I will have 600 queued jobs waiting for resources when the load on the cluster is high and this is when things get clumsy.

For this particular point, there may be something to do in dask-jobqueue: prevent dask-jobqueue to launch too many jobs if they're not starting. This does not sound really easy though.

Can I just ask if the 600 workers/jobs you want are configured too use one full node? At this scale, it is better to book one complete node in each job. e.g. if the nodes on your cluster have 36 cores, use
```python
cluster = FooCluster(cores=36, processes=18, memory='196GB', ...)
cluster.scale(600)
```
rather than
```python
cluster = FooCluster(cores=2, processes=1, memory='10GB', ...)
cluster.scale(600)
```

**Comment by MarieNyst** [comment]
Thank you for your answer.
The solution you propose indeed helps in my situation.

> prevent dask-jobqueue to launch too many jobs if they're not starting. This does not sound really easy though.

This, I think, would be very useful and solve the issue in any setup.

**Comment by guillaumeeb** [comment]
I'm closing this since we (at least I) don't plan working on preventing to launch too many jobs in queue right now.
