### ISSUE TITLE
Compare and Contrast with Dask-DRMAA

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-jobqueue#5]
Both projects have evolved somewhat independently.  I imagine that each has logic that the other could use.

**Comment by guillaumeeb** [comment]
Maybe @lesteve could give some comment here? Should we leave this question issue open?

**Comment by lesteve** [comment]
At one point, I got the feeling that dask-jobqueue was the "more active project" while aiming for the same functionality as dask-drmaa so I put my effort into dask-jobqueue. At the time, I followed dask-drmaa for a few months because some issues in dask-drmaa were relevant in dask-jobqueue as well.

The main difference as far as I am aware is whether you rely on DRMAA as the compatibility layer between the different schedulers (dask-drmaa approach) or decide to write the scheduler-specific code yourself (dask-jobqueue approach).

Maybe @jakirkham can comment whether he knows of some missing functionalities in dask-jobqueue or anything else that could prevent a dask-drmaa user to switch to dask-jobqueue.

**Comment by sntgluca** [comment]
Two cents on this topic from a new dask user:
@lesteve described the role of DRMAA very nicely from the developer side.

From an user point of view, I simply consider DRMAA _yet another way_ of submitting jobs to a HPC environment, with pros and cons. In oder words, DRMAA can be seen as an example of a _scheduler_.

Personally, I would think a DrmaaCluster class would fit the model of this package as well as SGECluster and the others. I hope I am not completely off...

**Comment by mrocklin** [comment]
Adding a DrmaaCluster to this repository seems in-scope to me.

**Comment by guillaumeeb** [comment]
I don't know DRMAA at all, but if it looks feasible to you @sntgluca, it certainly is worth the try! 

Maybe we can close this issue as @lesteve gave his opinion, and just open a new one to create  DrmaaCluster.

**Comment by lesteve** [comment]
The thing I am not sure about is how DRMAA would fit with the existing code base. Currently all the `*Cluster` classes mostly have to answer these questions:
- what's the command equivalent to `qsub`
- what's the command equivalent to `qdel`
- how do you pass resources specs: number of cores, memory, etc ...
- how do you parse the `qsub` output to get the job id

My understanding (I may be wrong) is that DRMAA does not really follow this pattern, i.e. there is not a `qsub` equivalent command but it gives you an API that you can use to submit jobs instead.

Personally, I have to admit I find it a bit akward to have two ways of submitting to the same HPC cluster in the same project. I guess this would be an additional (optional) dependency on drmaa-python bindings https://github.com/pygridtools/drmaa-python which is something to think about for maintainability.

> From an user point of view, I simply consider DRMAA yet another way of submitting jobs to a HPC environment, with pros and cons.

@sntgluca maybe it would help if you could elaborate on the "pros and cons" of DRMAA vs using the class for your scheduler, say `SGECluster`. Have you tried `dask-drmaa`? Are there some things you could do with `DRMAACluster` that you can not do with `SGECluster` for some good reasons.

**Comment by guillaumeeb** [comment]
Closing this as stale and answered. If anyone needs a DrmaaCluster, feel free to open another issue!
