### ISSUE TITLE
CI workflow docker-images-build is failing

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#516]
It looks like the periodic docker images build introduced in https://github.com/dask/dask-jobqueue/pull/455 has been failing for some times.

Error is:
```bash
Login Succeeded
The push refers to repository [docker.io/daskdev/dask-jobqueue]
b5b3f2d2ccfa: Preparing
fb3a76718e76: Preparing
71d58095ff75: Preparing
0bc01177df87: Preparing
a472d7850a9d: Preparing
aba8b9b7a6f0: Preparing
d3730c851267: Preparing
9df6c9762ee0: Preparing
19106930a708: Preparing
3c861f529340: Preparing
eba3a3350248: Preparing
77b174a6a187: Preparing
aba8b9b7a6f0: Waiting
d3730c851267: Waiting
9df6c9762ee0: Waiting
19106930a708: Waiting
3c861f529340: Waiting
eba3a3350248: Waiting
77b174a6a187: Waiting
denied: requested access to the resource is denied
```

Maybe there is a problem in the access token to daskdev on dockerhub?

cc @jacobtomlinson @andersy005 who worked on that.

**Comment by andersy005** [comment]
I don't have access to the dockerhub account and GitHub repo settings but my hunch is that this has to do with the dockerhub credentials... @jacobtomlinson may be able to confirm whether the daskdev dockerhub account credentials were updated lately....

**Comment by jacobtomlinson** [comment]
Docker Hub changed its free account rules a while back so that an org can only contain 3 people. We discovered this when we tried adding @jrbourbeau recently. During that exploration I accidentally removed the `daskdev` user from the org and am unable to add it back in. I had assumed it was a dummy account that I had created and wasn't being used. Sorry!

@guillaumeeb and @lesteve are still members of the org (we have 7 members that were grandfathered in) so one of you will need to generate a new API key and update things here.

Sorry again!

**Comment by guillaumeeb** [comment]
Thanks for the explanation @jacobtomlinson. So Ï updated secrets following the guide here: https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository. And it's back to green! 

If you ever need to delete our membership to daskdev, please ask, but I guess that as we have been added a while back, it's OK?

Also, just for the record, there seem to be a better integrated way of pushing docker images with Github actions; https://docs.github.com/en/actions/guides/publishing-docker-images#publishing-images-to-docker-hub. But we probably don't really need it (or we may need something else with docker-compose?).
