### ISSUE TITLE
Pooling Docker test images

### ISSUE THREAD

**Issue by jakirkham** [dask/dask-jobqueue#52]
As dask-drmaa and dask-jobqueue are both making use of Docker images for testing against job schedulers, wondering if we can pool these Docker files somewhere. Also might be good to build these in advance and host them on Docker Hub or Quay so that we can just pull them down for testing on CIs instead of rebuilding them from scratch each time.

**Comment by guillaumeeb** [comment]
For the PBS part, I'm trying talk with PBSPro organization to make them improve their images, so that we can depend on it, see http://community.pbspro.org/t/pbs-public-docker-image-improvement/887 discussion. 

More generally, do we have some namespace in dockerhub where to put these images, or do we want to host them in user namespaces?

**Comment by mrocklin** [comment]
There is a daskdev namespace on dockerhub

**Comment by mrocklin** [comment]
I'd be happy to hand out credentials for that if people like

**Comment by guillaumeeb** [comment]
Thinking about this, because the Travis build time can be quite long.

If we push some of our image to Dockerhub, how will we update them? Will we need to update them?

I see several possibilities:

- Push images that contains only the non Conda and Dask part, e.g. only the schedulers. We can push a sge-master and sge-slave image, for PBS it is also possible to pus a PBS:14.1.2 image. For Slurm we already do this. We then just install conda on top of that. Slurm is the fatest build, but it still takes close to 300 seconds to build the conda part of the docker image!
- We build images with scheduler + conda env, without dask (and eventually other key modules). 
- We build images with everything, except dask-jobqueue.

For the two last options: what versions should we pin? Can we still have a kind of automated image build if one of our major dependency is updated (e.g. distributed or dask), or will we have to do it manually? Could we for example rely on requirement.txt to rebuild image only when modified?

**Comment by mrocklin** [comment]
We can also use pip to update modules.  It is much faster :)

**Comment by jakirkham** [comment]
If you're ok not having a solver that is... 😕

**Comment by mrocklin** [comment]
Which, for our simple case, may be true.  Especially if that solver is
adding five minutes to the testing time.

**Comment by guillaumeeb** [comment]
So you're proposing to have pre-built images with everyting, and just pip update (or the equivalent with conda) key modules like dask and distributed?

Where would we store the Dockerfiles? We would build and push this images manually? How often?

**Comment by jhamman** [comment]
I think a logical first step would be to push the pbs, slurm, etc images to docker hub. That will really help simplify things on our end and will be a good first step toward speeding things up in the CI tests. Once that is done, we can go over how to install dependencies.

**Comment by mrocklin** [comment]
We could also use the caching mechanism in circle-ci.  We do this for
dask-kubernetes and it seems to work well.

**Comment by guillaumeeb** [comment]
As @lesteve mentionned in #215, there is a PBS Docker image tagged correctly available in Dockerhub https://hub.docker.com/r/pbspro/pbspro/tags.

**Comment by lesteve** [comment]
We are now using Docker images on dockerhub thanks to #432, closing.
