### ISSUE TITLE
FutureWarning: tmpfile is deprecated

### ISSUE THREAD

**Issue by tensionhead** [dask/dask-jobqueue#557]
**What happened**:

Plain import produces multi-line `FutureWarning` with newest dask and dask_jobqueue version. Multiple calls (e.g. for unit testing) pollute the terminal output with many of those.

**What you expected to happen**:

No `FutureWarning`

**Minimal Complete Verifiable Example**:

```python
import dask_jobqueue
>>> lib/python3.8/site-packages/dask_jobqueue/core.py:20: FutureWarning: tmpfile is deprecated and will be removed in a future release. Please use dask.utils.tmpfile instead.
  from distributed.utils import tmpfile
```
**Anything else we need to know?**:

Happens on all tested platforms (various *nix, Mac OS)

**Environment**: 

- Dask version: 2022.5.0
- Python version: 3.8.13
- Operating System: Mac OS 12.2 / Ubuntu 20.04
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment]
Thanks for opening up an issue @tensionhead. It looks like this was already fixed in https://github.com/dask/dask-jobqueue/pull/529, but hasn't been released yet. There's a discussion around releasing over in https://github.com/dask/dask-jobqueue/issues/555. Closing as the appropriate changes have already been made in `main`
