### ISSUE TITLE
signal errors when importing dask_jobqeueue from a thread

### ISSUE THREAD

**Issue by zulissimeta** [dask/dask-jobqueue#667]
If you load dask_jobqueue from a thread (for example, if using with `prefect`), you will get errors due to the signal. 

Code: https://github.com/dask/dask-jobqueue/blob/a88e073e960082496df69ae2bc4b4dd6409e6617/dask_jobqueue/runner.py#L18

Partial trace:
```
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: signal only works in main thread of the main interpreter
```

I haven't dug into the logic of how this is used and/or why it's needed. Maybe we should only do this if we are in the main thread?

**Comment by jacobtomlinson** [comment]
Thanks for raising this! That was added because we were seeing hangs during shutdown without it (see https://github.com/dask/distributed/issues/8644).

You might be right that we only need to do this if we are running in the main thread. I've opened #668 to do this. Would you mind installing the version from that PR and trying it out with Prefect to see if it a) solves your problem and b) doesn't cause the hangs we were seeing previously.

```bash
# Install the PR version
pip install git+https://github.com/dask/dask-jobqueue.git@refs/pull/668/merge
```

**Comment by zulissimeta** [comment]
Thanks for the quick patch; confirming this fixed the problem!

**Comment by jacobtomlinson** [comment]
Great. I'll merge that PR then!
