### ISSUE TITLE
Stopping worker and stopping whole jobqueue cluster

### ISSUE THREAD

**Issue by guillaumeeb** [dask/dask-jobqueue#83]
The question is what is the right way to do this?

Currently, when I want to stop my JobQueue cluster to restart a fresh one (with new parameters for instance), I use
````
cluster.scheduler.close()
````
For stopping workers, as the scale method is not currently working, I use something like 
````
cluster.stop_wokers(cluster.jobs)
````
(I don't remember the exact syntax, and not eager to look for it).

Are these the right things to do?

Should we expose some more explicit methods, for example:
````
cluster.stop()
````
and
````
cluster.stop_all_workers()
````

**Comment by lesteve** [comment]
> For stopping workers, as the scale method is not currently working, I use something like
> `cluster.stop_wokers(cluster.jobs)`

I have been using something like this as well, and I agree it would be nice to have a simpler interface. Another approach which I think is working, typically in a notebook, you reexecute the cell that defines cluster + client. I am not sure how this works behind the scene (my understanding is that this is because of death-timeout in dask workers) but after some time, the workers from the old cluster gets killed.

**Comment by mrocklin** [comment]
When a cluster is GCed it kills its workers.  If for some reason this
doesn't happen (such as at the end of a process) then yes, the workers will
kill themselves if they have not heard from the scheduler in the
death-timeout period (60s by default)
